server.port: 9999
spring:
  jpa:
      hibernate:
        ddl-auto: update
      properties:
         hibernate:
           dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/CommandCenter
    username: root
    password:
